version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    #ports:
    #- 27017:27017
  
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - ./data/users.sql:/docker-entrypoint-initdb.d/users.sql

  frontend:
    env_file:
      - ./frontend/.env.prod
    container_name: frontend
    build: ./frontend
    ports:
      - 80:80

  product:
    env_file:
      - ./product/.env.prod
    container_name: product
    build: ./product
    depends_on:
      - mongodb
      - postgres
    ports:
      - 4000:4000

  user:
    env_file:
      - ./user/.env.prod
    container_name: user
    build: ./user
    depends_on:
      - mongodb
      - postgres

  auth:
    env_file:
      - ./auth/.env.prod
    container_name: auth
    build: ./auth
    depends_on:
      - mongodb
      - postgres

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - product
      - user
      - auth
    ports:
      - 8080:80

  # Add any new services below 