version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest

  frontend:
    env_file:
      - ./frontend/.env.prod
    container_name: frontend
    build: ./frontend
    ports:
      - 80:80

  backend:
    env_file:
      - ./backend/.env.prod
    container_name: backend
    build: ./backend
    depends_on:
      - mongodb

  user:
    env_file:
      - ./user/.env.prod
    container_name: user
    build: ./user
    depends_on:
      - mongodb

  auth:
    env_file:
      - ./auth/.env.prod
    container_name: auth
    build: ./auth
    depends_on:
      - mongodb

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - backend
      - user
      - auth
    ports:
      - 8080:80

  # Add any new services below 