version: "3"
services:
  mongodb:
    container_name: mongo-database
    image: mongo:latest

  frontend-service:
    env_file:
      - ./frontend/.env
    container_name: frontend-service
    build: ./frontend
    ports:
      - 80:80

  backend-service:
    env_file:
      - ./backend/.env
    container_name: backend-service
    build: ./backend
    depends_on:
      - mongodb
    ports:
      - 4000

  user-service:
    env_file:
      - ./user/.env
    container_name: user-service
    build: ./user
    depends_on:
      - mongodb
    ports:
      - 4001

  auth-service:
    env_file:
      - ./auth/.env
    container_name: auth-service
    build: ./auth
    depends_on:
      - mongodb
    ports:
      - 4002

  # Add any new services below 