version: "3"
services:
  mongodb:
    container_name: mongo-database
    image: mongo:latest


  backend-service:
    env_file:
      - ./backend/.env
    container_name: backend-service
    build: ./backend
    depends_on:
      - mongodb
    ports:
      - 4000:4000