name: Continuous Deployment Workflow - Express
on:
  push:
    branches:
      - main # Run the workflow only on push to the main branch
    paths:
      - 'express/**' # Workflow triggered on changes to code within express directory
      - '.github/workflows/express_cd.yml'

jobs:
  test:
    defaults:
        run:
            working-directory: ./express

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}